# Generated by Django 5.2 on 2026-02-25 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0002_alter_customuser_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='payment_method',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='subscription_expiry',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bot_exp',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bot_number',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='sub_format',
            field=models.CharField(choices=[('Aucun', 'Aucun abonnement'), ('free', '24 heures'), ('500', '14 Jours'), ('1000', '30 Jours')], default='Aucun', max_length=20),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='ver_code',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
