# Generated by Django 5.2 on 2026-03-02 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_sys', '0003_customuser_payment_method_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='sub_format',
            field=models.CharField(choices=[('Aucun', 'Aucun abonnement'), ('free', '24 heures'), ('500', '14 Jours'), ('1000', '30 Jours')], default='free', max_length=20),
        ),
    ]
