# Generated by Django 5.2 on 2026-03-05 07:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payements', '0002_rename_payment_payments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payments',
            name='amount',
            field=models.DecimalField(decimal_places=0, max_digits=10),
        ),
    ]
